config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :properties

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first

    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.user = current_user

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property_type, :property_sale_or_rental, :property_price_per_month, :property_price_for_sale, :property_rental_deposit, :property_first_line_address, :property_postcode, :property_region, :property_listing_type, :property_number_of_bedrooms, :property_number_of_bathrooms, :property_size_in_metres, :property_condition, :property_near_banks, :property_is_new_build, :property_has_elevator, :property_has_garage, :property_has_private_pool, :property_has_communal_pool, :property_has_terrace, :property_has_photos, :property_has_airconditioning, :property_has_garden, :property_has_storage, :property_has_wardrobes, :property_floor, :user_id, :property_photos)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include ApplicationHelper

  def facebook

    # Attempt to find the User
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # This will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      #session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Primecyprus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/properties/_form.html.erb
<%= form_for @property, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :property_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_sale_or_rental, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_sale_or_rental, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_price_per_month, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_price_per_month, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_price_for_sale, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_price_for_sale, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_rental_deposit, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_rental_deposit, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_first_line_address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_first_line_address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_postcode, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_postcode, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_region, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_region, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_listing_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_listing_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_number_of_bedrooms, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :property_number_of_bedrooms, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_number_of_bathrooms, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :property_number_of_bathrooms, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_size_in_metres, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_size_in_metres, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_condition, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_condition, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_near_banks, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_near_banks, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_is_new_build, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_is_new_build, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_elevator, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_elevator, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_garage, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_garage, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_private_pool, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_private_pool, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_communal_pool, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_communal_pool, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_terrace, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_terrace, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_photos, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_photos, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_airconditioning, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_airconditioning, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_garden, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_garden, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_storage, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_storage, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_has_wardrobes, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :property_has_wardrobes, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_floor, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_floor, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_photos, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :property_photos, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  properties_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Property %></h1>
</div>
<%= render :partial => 'form' %>

app/views/properties/index.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => Property %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:property_type) %></th>
      <th><%= model_class.human_attribute_name(:property_sale_or_rental) %></th>
      <th><%= model_class.human_attribute_name(:property_price_per_month) %></th>
      <th><%= model_class.human_attribute_name(:property_price_for_sale) %></th>
      <th><%= model_class.human_attribute_name(:property_rental_deposit) %></th>
      <th><%= model_class.human_attribute_name(:property_first_line_address) %></th>
      <th><%= model_class.human_attribute_name(:property_postcode) %></th>
      <th><%= model_class.human_attribute_name(:property_region) %></th>
      <th><%= model_class.human_attribute_name(:property_listing_type) %></th>
      <th><%= model_class.human_attribute_name(:property_number_of_bedrooms) %></th>
      <th><%= model_class.human_attribute_name(:property_number_of_bathrooms) %></th>
      <th><%= model_class.human_attribute_name(:property_size_in_metres) %></th>
      <th><%= model_class.human_attribute_name(:property_condition) %></th>
      <th><%= model_class.human_attribute_name(:property_near_banks) %></th>
      <th><%= model_class.human_attribute_name(:property_is_new_build) %></th>
      <th><%= model_class.human_attribute_name(:property_has_elevator) %></th>
      <th><%= model_class.human_attribute_name(:property_has_garage) %></th>
      <th><%= model_class.human_attribute_name(:property_has_private_pool) %></th>
      <th><%= model_class.human_attribute_name(:property_has_communal_pool) %></th>
      <th><%= model_class.human_attribute_name(:property_has_terrace) %></th>
      <th><%= model_class.human_attribute_name(:property_has_photos) %></th>
      <th><%= model_class.human_attribute_name(:property_has_airconditioning) %></th>
      <th><%= model_class.human_attribute_name(:property_has_garden) %></th>
      <th><%= model_class.human_attribute_name(:property_has_storage) %></th>
      <th><%= model_class.human_attribute_name(:property_has_wardrobes) %></th>
      <th><%= model_class.human_attribute_name(:property_floor) %></th>
      <th><%= model_class.human_attribute_name(:property_photos) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.id %></td>
        <td><%= property.property_type %></td>
        <td><%= property.property_sale_or_rental %></td>
        <td><%= property.property_price_per_month %></td>
        <td><%= property.property_price_for_sale %></td>
        <td><%= property.property_rental_deposit %></td>
        <td><%= property.property_first_line_address %></td>
        <td><%= property.property_postcode %></td>
        <td><%= property.property_region %></td>
        <td><%= property.property_listing_type %></td>
        <td><%= property.property_number_of_bedrooms %></td>
        <td><%= property.property_number_of_bathrooms %></td>
        <td><%= property.property_size_in_metres %></td>
        <td><%= property.property_condition %></td>
        <td><%= property.property_near_banks %></td>
        <td><%= property.property_is_new_build %></td>
        <td><%= property.property_has_elevator %></td>
        <td><%= property.property_has_garage %></td>
        <td><%= property.property_has_private_pool %></td>
        <td><%= property.property_has_communal_pool %></td>
        <td><%= property.property_has_terrace %></td>
        <td><%= property.property_has_photos %></td>
        <td><%= property.property_has_airconditioning %></td>
        <td><%= property.property_has_garden %></td>
        <td><%= property.property_has_storage %></td>
        <td><%= property.property_has_wardrobes %></td>
        <td><%= property.property_floor %></td>
        <td><%= property.property_photos %></td>
        <td><%=l property.created_at, format: :long %></td>
        <td>
          <%= link_to property_path(property), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to property_path(property), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_property_path,
            :class => 'btn btn-primary' %>

app/views/properties/new.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Property %></h1>
</div>
<%= render :partial => 'form' %>

app/views/properties/show.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => Property %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_type) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_sale_or_rental) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_sale_or_rental %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_price_per_month) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_price_per_month %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_price_for_sale) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_price_for_sale %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_rental_deposit) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_rental_deposit %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_first_line_address) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_first_line_address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_postcode) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_postcode %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_region) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_region %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_listing_type) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_listing_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_number_of_bedrooms) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_number_of_bedrooms %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_number_of_bathrooms) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_number_of_bathrooms %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_size_in_metres) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_size_in_metres %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_condition) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_condition %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_near_banks) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_near_banks %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_is_new_build) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_is_new_build %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_elevator) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_elevator %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_garage) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_garage %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_private_pool) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_private_pool %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_communal_pool) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_communal_pool %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_terrace) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_terrace %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_photos) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_photos %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_airconditioning) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_airconditioning %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_garden) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_garden %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_storage) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_storage %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_has_wardrobes) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_has_wardrobes %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_floor) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_floor %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:property_photos) %></dt>
      <dd><pre class="prettyprint"><%= @property.property_photos %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              properties_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_property_path(@property), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              property_path(@property),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>